/**
 * products.js — Catálogo de GPS Portátiles
 * Única fuente de verdad para catálogo, tarjetas y ficha de producto.
 */

const CATEGORIA_LABEL = {
  personas: "Personas",
  vehiculos: "Vehículos",
  mascotas: "Mascotas",
  objetos: "Objetos de valor",
};

const PRODUCTS = [
  {
    id: "rastreador-personal-mini",
    sku: "GP-PER-100",
    subtitulo: "El rastreador ideal para acompañar a quienes más quieres, todo el día.",
    categoria: ["personas", "objetos"],
    nombre: "Rastreador Personal Mini 4G",
    linea: "Línea Personal",
    precio: 5490,
    precioAnterior: null,
    rating: 4.7,
    reviews: 128,
    disponibilidad: "in-stock",
    disponibilidadTexto: "Pocas unidades",
    bateriaDias: "Hasta 5 días con uso diario (aprox. 1 hora activa al día)",
    imagen: "personal",
    model3d: "assets/3d/gps-personal.html?v=2",
    resenas: [
      { nombre: "Ramón Peña", ciudad: "Santiago, RD", foto: "assets/images/reviews/personal-mini-1.jpg", rating: 5, texto: "Me cabe en la palma de la mano, literal. Se lo puse a mi papá en la cartera y no ha vuelto a perderse." },
      { nombre: "Yolanda Ferreira", ciudad: "Moca, RD", foto: "assets/images/reviews/personal-mini-2.jpg", rating: 5, texto: "La cajita se ve bien presentada, como de marca de verdad. Llegó todo completo y fácil de configurar." },
      { nombre: "Katherine Reyes", ciudad: "La Vega, RD", foto: "assets/images/reviews/personal-mini-3.jpg", rating: 4, texto: "Se lo metí a la mochila de mi hija para el colegio, bien chiquito y no se nota para nada." },
    ],
    bullets: [
      "Ubicación en tiempo real vía red 4G LTE",
      "Tarjeta SIM ya integrada, lista para usar",
      "Resistente al agua según norma IP65",
    ],
    descripcionCorta: "Localizador compacto para adultos mayores, niños y objetos de valor, con SIM ya integrada.",
    metaDescripcion: "Localizador GPS 4G compacto para personas mayores, niños y objetos de valor. SIM ya integrada, resistente al agua IP65. Envío gratis en RD.",
    descripcionLarga:
      "Un localizador compacto (41 g) pensado para pasar desapercibido en un bolsillo o llavero. Trae la tarjeta SIM ya preconfigurada, así que no hay que gestionar un chip aparte: se activa el plan de rastreo y queda reportando ubicación en tiempo real por red 4G, con una batería que aguanta hasta 5 días de uso diario normal.",
    caracteristicas: [
      "Ubicación en tiempo real por red 4G LTE con respaldo GSM/GPRS",
      "Precisión de hasta 5 metros según recepción de señal GPS",
      "Geocercas (zonas seguras) con notificación de entrada o salida",
      "Alertas de batería baja, apagado, velocidad y movimiento",
      "Resistencia al agua según norma IP65",
    ],
    compatibilidad: "Incluye tarjeta SIM ya preconfigurada. Requiere una suscripción activa al plan de rastreo para reportar ubicación. App para iOS y Android.",
    cobertura: "Cobertura internacional con red 4G, según el plan de rastreo activo.",
    red: "4G LTE / GSM / GPRS",
    peso: "41 g",
    dimensiones: "5.4 × 3.1 × 2.0 cm",
    caja: ["1 rastreador GPS", "Tarjeta SIM ya integrada", "Cable de carga USB-C", "Guía rápida"],
    garantia: "6 meses contra defectos de fábrica",
    ventajas: ["Ya viene con SIM integrada, no hay que gestionar un chip aparte", "Diseño compacto y liviano (41 g)", "Resistente al agua IP65"],
    desventajas: ["Requiere una suscripción activa al plan de rastreo para funcionar", "La autonomía baja si el rastreo en tiempo real queda siempre activo"],
    idealPara: "Adultos mayores, niños, equipaje y objetos de valor.",
    faqs: [
      { p: "¿Necesito pagar una suscripción?", r: "El dispositivo ya incluye la SIM, pero para que reporte ubicación necesita un plan de rastreo activo." },
      { p: "¿Cuánto dura la batería?", r: "Hasta 5 días con un uso normal de rastreo diario (aprox. 1 hora activa por día)." },
    ],
  },
  {
    id: "gps-vehicular-oculto",
    sku: "GP-VEH-200",
    subtitulo: "Se conecta en segundos y queda completamente oculto en tu vehículo.",
    categoria: ["vehiculos"],
    nombre: "GPS Vehicular Oculto OBD-2",
    linea: "Línea Vehicular",
    precio: 4550,
    precioAnterior: null,
    rating: 4.8,
    reviews: 214,
    disponibilidad: "in-stock",
    disponibilidadTexto: "Pocas unidades",
    bateriaDias: "Sin recargas — se alimenta del vehículo (respaldo interno de hasta 30 min si se desconecta)",
    imagen: "vehicular",
    model3d: "assets/3d/gps-obd2.html?v=2",
    resenas: [
      { nombre: "Luis Almonte", ciudad: "Santo Domingo, RD", foto: "assets/images/reviews/vehicular-obd2-1.jpg", rating: 5, texto: "SAFETAG en la caja, se ve serio. Lo conecté yo mismo al OBD en cinco minutos." },
      { nombre: "Pedro Julio Vargas", ciudad: "San Cristóbal, RD", foto: "assets/images/reviews/vehicular-obd2-2.jpg", rating: 5, texto: "Bien pequeño para lo que promete, no se nota para nada desde afuera del carro." },
      { nombre: "Anderson De la Cruz", ciudad: "Bonao, RD", foto: "assets/images/reviews/vehicular-obd2-3.jpg", rating: 4, texto: "Lo instalé en dos camionetas del negocio, el número de serie viene bien marcado para no confundir cuál es cuál." },
    ],
    bullets: [
      "Se conecta directo al puerto OBD-II, sin cables",
      "Se alimenta del vehículo, sin recargas manuales",
      "Batería de respaldo si se desconecta",
    ],
    descripcionCorta: "Se conecta directo al puerto OBD-II del vehículo, sin cables ni instalación.",
    metaDescripcion: "GPS oculto para autos que se conecta al puerto OBD-2 en segundos, sin cables ni instalación. Se alimenta del vehículo. Envío gratis a toda RD.",
    descripcionLarga:
      "Se conecta en segundos al puerto de diagnóstico OBD-II que traen la mayoría de los autos desde 1996, sin cables ni herramientas. Queda alimentado directamente por la batería del vehículo y reporta su ubicación en tiempo real por red 4G, con una batería de respaldo interna que lo mantiene reportando hasta 30 minutos si lo desconectan o lo remueven del puerto.",
    caracteristicas: [
      "Instalación tipo plug & play en el puerto OBD-II, sin cables",
      "Alimentación directa desde el vehículo, sin recargas manuales",
      "Batería de respaldo interna (hasta 30 min) ante una desconexión",
      "Alertas de exceso de velocidad, vibración y remoción del puerto",
      "Compatible con un amplio rango de voltaje (9–36V): autos, camionetas y flotillas",
    ],
    compatibilidad: "Compatible con vehículos con puerto OBD-II estándar (la mayoría de autos desde 1996). Panel web y app móvil incluidos.",
    cobertura: "Cobertura donde exista señal celular 4G, con reporte en tiempo real.",
    red: "4G LTE",
    peso: "45 g",
    dimensiones: "5.0 × 3.0 × 2.0 cm",
    caja: ["1 rastreador GPS OBD-II", "Guía de instalación", "Funda protectora"],
    garantia: "6 meses, incluye soporte técnico remoto",
    ventajas: ["Se instala solo, en segundos, sin herramientas", "No requiere recargas: se alimenta del vehículo", "Discreto dentro del tablero, difícil de notar a simple vista"],
    desventajas: ["Solo compatible con vehículos que tengan puerto OBD-II estándar", "Si lo desconectan del puerto, la batería de respaldo dura poco (30 min)"],
    idealPara: "Autos particulares, camionetas de trabajo y flotillas pequeñas con puerto OBD-II.",
    faqs: [
      { p: "¿Necesito conectarlo a la batería del auto?", r: "No, se conecta directo al puerto OBD-II y se alimenta desde ahí; no requiere cableado adicional." },
      { p: "¿Qué pasa si lo desconectan?", r: "Tiene una batería de respaldo interna que lo mantiene reportando ubicación hasta por 30 minutos tras la desconexión." },
    ],
  },
  {
    id: "rastreador-mini-tag",
    sku: "GP-TAG-300",
    subtitulo: "El rastreador más pequeño y discreto para proteger lo que más te importa.",
    categoria: ["objetos", "mascotas"],
    nombre: "Rastreador Mini TAG",
    linea: "Línea Mini Tag",
    caracteristicasDestacadas: [
      { svg: '<circle cx="12" cy="12" r="10" fill="#FBBC05"/><circle cx="12" cy="9" r="3" fill="#fff"/><path d="M6 19c0-3.3 2.7-5 6-5s6 1.7 6 5" fill="#fff"/>', label: "Vista de calle en vivo" },
      { svg: '<path d="M6 3v9a6 6 0 0012 0V3" fill="none" stroke="#EF4444" stroke-width="2.4" stroke-linecap="round"/><path d="M6 3h3.4M14.6 3H18" stroke="#EF4444" stroke-width="2.4" stroke-linecap="round"/><rect x="5.4" y="8.8" width="4" height="3" rx="0.5" fill="#E5E7EB"/><rect x="14.6" y="8.8" width="4" height="3" rx="0.5" fill="#E5E7EB"/>', label: "Magnético" },
      { svg: '<rect x="2" y="7" width="17" height="10" rx="2.5" fill="none" stroke="#22C55E" stroke-width="2"/><rect x="4.3" y="9.3" width="9" height="5.4" rx="1" fill="#22C55E"/><rect x="20.2" y="10" width="2" height="4" rx="0.8" fill="#22C55E"/>', label: "3 años de batería" },
      { svg: '<circle cx="6" cy="19" r="2" fill="#4C7DFF"/><circle cx="18" cy="5" r="2" fill="#4C7DFF"/><path d="M8 19h7a4 4 0 004-4v-1a4 4 0 00-4-4H9a4 4 0 01-4-4V5" fill="none" stroke="#4C7DFF" stroke-width="2" stroke-linecap="round"/>', label: "Historial de recorrido" },
      { svg: '<circle cx="12" cy="12" r="10" fill="#22C55E"/><path d="M12 7v10M9.3 9.2c0-1.3 1.2-1.9 2.7-1.9s2.7.8 2.7 1.9c0 2.4-5.4 1.4-5.4 3.9 0 1.1 1.2 1.9 2.7 1.9s2.7-.6 2.7-1.9" fill="none" stroke="#fff" stroke-width="1.6" stroke-linecap="round"/>', label: "Sin pagos mensuales" },
      { svg: '<circle cx="12" cy="12" r="10" fill="#4C7DFF"/><path d="M2 12h20M12 2a15 15 0 010 20M12 2a15 15 0 000 20" fill="none" stroke="#fff" stroke-width="1.6"/>', label: "Cobertura internacional" },
      { svg: '<rect x="4" y="11" width="16" height="10" rx="2.5" fill="#334155"/><path d="M7.5 11V7.5a4.5 4.5 0 019 0V11" fill="none" stroke="#334155" stroke-width="2"/><circle cx="12" cy="16" r="1.7" fill="#fff"/>', label: "Discreto" },
      { svg: '<path fill="#25D366" d="M12 2C6.48 2 2 6.48 2 12c0 1.85.5 3.58 1.35 5.06L2 22l5.12-1.34A9.94 9.94 0 0012 22c5.52 0 10-4.48 10-10S17.52 2 12 2Z"/><path fill="#fff" d="M9.1 7.6c-.2-.45-.4-.46-.6-.47h-.5c-.18 0-.46.07-.7.34-.24.27-.9.9-.9 2.16 0 1.27.93 2.5 1.06 2.67.13.17 1.8 2.88 4.45 3.92 2.2.87 2.65.7 3.13.66.48-.05 1.54-.63 1.76-1.24.22-.6.22-1.13.15-1.24-.06-.1-.24-.17-.5-.3s-1.55-.76-1.79-.85c-.24-.09-.42-.13-.6.13-.17.26-.68.85-.83 1.02-.15.18-.3.2-.56.07-.26-.13-1.08-.4-2.05-1.27-.76-.68-1.27-1.5-1.42-1.76-.15-.26-.02-.4.11-.53.12-.12.26-.3.4-.46.13-.15.17-.26.26-.43.09-.17.04-.33-.02-.46-.06-.13-.58-1.46-.81-2Z"/>', label: "Bot de WhatsApp" },
      { svg: '<circle cx="12" cy="12" r="10" fill="#29A9EB"/><path fill="#fff" d="M17.7 7.2 15.9 17c-.13.6-.5.75-1 .47l-2.77-2.04-1.34 1.29c-.15.15-.27.27-.56.27l.2-2.83 5.16-4.66c.22-.2-.05-.31-.35-.11l-6.38 4.02-2.75-.86c-.6-.19-.6-.6.13-.89l10.75-4.14c.5-.18.94.12.78.9Z"/>', label: "Bot de Telegram" },
      { svg: '<path d="M12 2a7 7 0 00-7 7c0 5.25 7 13 7 13s7-7.75 7-13a7 7 0 00-7-7Z" fill="#EF4444"/><circle cx="12" cy="9" r="2.6" fill="#fff"/>', label: "Ubicación compartida sin límites" },
      { svg: '<circle cx="12" cy="12" r="10" fill="#F59E0B"/><path d="M12 6a4.5 4.5 0 00-4.5 4.5c0 3.6-1.5 4.3-1.5 5h12s-1.5-.7-1.5-5A4.5 4.5 0 0012 6z" fill="none" stroke="#fff" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/><path d="M10.5 17.5a1.5 1.5 0 003 0" fill="none" stroke="#fff" stroke-width="1.5" stroke-linecap="round"/>', label: "Alertas salidas de zonas" },
      { svg: '<circle cx="12" cy="12" r="10" fill="#4C7DFF"/><path d="M12 6.5c-2 1.3-3.3 1.6-5 1.6V13c0 3.2 2.1 5.6 5 6.5 2.9-.9 5-3.3 5-6.5V8.1c-1.7 0-3-.3-5-1.6z" fill="#fff"/>', label: "Conexión totalmente discreta" },
    ],
    precio: 2490,
    precioAnterior: null,
    rating: 4.6,
    reviews: 96,
    disponibilidad: "in-stock",
    disponibilidadTexto: "Pocas unidades",
    bateriaDias: "Hasta 3 años de batería, sin recargas",
    imagen: "mascota",
    model3d: "assets/3d/gps-redondo.html?v=2",
    resenas: [
      { nombre: "Manuel Batista", ciudad: "Moca, RD", foto: "assets/images/reviews/reviewer-2-avatar.jpg", rating: 5, texto: "Pensé que era más grande, pero me sorprendió. ¡Es súper pequeño! Ideal para lo que lo quería." },
      { nombre: "Elizabeth Cruz", ciudad: "Santiago, RD", foto: "assets/images/reviews/reviewer-1-avatar.jpg", rating: 5, texto: "Jajaja, bueno... ojalá que mi esposo no me esté ocultando nada. Quedó súper bien escondido debajo del asiento del vehículo." },
      { nombre: "Carolina Núñez", ciudad: "Santo Domingo, RD", foto: "assets/images/reviews/reviewer-3-avatar.jpg", rating: 5, texto: "Compré varios para mis hijos y mis mascotas. Funcionan de maravilla, la aplicación es muy fácil de usar y ahora me siento mucho más tranquila porque sé dónde están todos." },
    ],
    bullets: [
      "Hasta 3 años de batería, sin recargas",
      "No requiere tarjeta SIM ni pagos mensuales",
      "Discreto: no lo detectan los escáneres de rastreadores de los celulares",
    ],
    descripcionCorta: "Localizador mini y discreto, con hasta 3 años de batería y sin pagos mensuales.",
    metaDescripcion: "Mini localizador GPS sin SIM ni mensualidad, batería de hasta 3 años. Ideal para llaves, mochilas, bicicletas y mascotas. Envío gratis en RD.",
    descripcionLarga:
      "Un localizador mini y discreto, del tamaño de una moneda grande, que puedes llevar en las llaves, la mochila, la bici o sujeto al collar de una mascota. A diferencia de otros rastreadores, no necesita tarjeta SIM ni una suscripción mensual: la batería dura hasta 3 años sin recargar. Guarda el historial de recorrido, avisa si sale de una zona segura configurada y funciona en cualquier país gracias a su conectividad internacional.",
    caracteristicas: [
      "Hasta 3 años de batería, sin necesidad de recarga",
      "No requiere tarjeta SIM ni pagos mensuales",
      "Historial de recorrido y ubicación precisa",
      "Alertas al salir de zonas seguras configuradas",
      "Conectividad internacional: funciona en cualquier país",
      "Discreto, no es detectado por los escáneres de rastreadores de los celulares",
    ],
    compatibilidad: "Compatible con app móvil para iOS y Android. No requiere SIM ni plan de datos.",
    cobertura: "Dispositivo magnético y extra pequeño",
    red: "Conectividad internacional propia (sin SIM ni datos móviles)",
    peso: "38 g",
    dimensiones: "4.5 × 3.2 × 1.6 cm",
    caja: ["1 localizador GPS", "Guía rápida", "Tutoriales", "Acceso a la app", "Garantía"],
    garantia: "6 meses",
    ventajas: ["Batería de hasta 3 años, no hay que recargarlo", "Sin pagos mensuales ni SIM que gestionar", "Discreto y difícil de detectar"],
    desventajas: ["Al no usar SIM propia, depende de la red de conectividad internacional del fabricante para reportar ubicación", "No incluye soporte de collar; para usarlo en una mascota hay que conseguir uno aparte"],
    idealPara: "Llaves, mochilas, bicicletas, mascotas y cualquier objeto que no quieras perder de vista.",
    faqs: [
      { p: "¿Necesito pagar una suscripción?", r: "No, este modelo no requiere tarjeta SIM ni pagos mensuales." },
      { p: "¿Cuánto dura la batería?", r: "Hasta 3 años según el uso, sin necesidad de recargarlo." },
      { p: "¿Otros celulares pueden detectar mi TAG?", r: "El TAG se vincula de forma privada con tu cuenta para ofrecer una experiencia más segura y discreta.", destacada: true },
    ],
  },
  {
    id: "rastreador-objetos-valor",
    sku: "GP-OBJ-600",
    subtitulo: "Se disfraza de cargador y protege lo que más valoras, sin que nadie lo note.",
    categoria: ["objetos", "vehiculos"],
    nombre: "GPS Oculto Tipo Cargador ValueTrack",
    linea: "Línea Objetos",
    precio: 4990,
    precioAnterior: null,
    rating: 4.5,
    reviews: 61,
    disponibilidad: "in-stock",
    disponibilidadTexto: "Pocas unidades",
    bateriaDias: "Batería de respaldo de 30 min si se desconecta de la toma de 12V",
    imagen: "objeto",
    model3d: "assets/3d/gps-cargador.html?v=2",
    resenas: [
      { nombre: "Massiel Guzmán", ciudad: "Puerto Plata, RD", foto: "assets/images/reviews/valuetrack-1.jpg", rating: 5, texto: "Está metido en el encendedor de mi carro y de verdad parece un cargador cualquiera." },
      { nombre: "Wilson Tavárez", ciudad: "Higüey, RD", foto: "assets/images/reviews/valuetrack-2.jpg", rating: 5, texto: "Llegó bien empacado, se nota que le pusieron cuidado a la caja." },
      { nombre: "Rosa Iris Familia", ciudad: "San Francisco de Macorís, RD", foto: "assets/images/reviews/valuetrack-3.jpg", rating: 4, texto: "Me gustó que además de rastrear tiene el puerto USB, así no pierdo espacio en el carro." },
    ],
    bullets: [
      "Se conecta directo a la toma de 12V, sin instalación",
      "Botón SOS físico integrado",
      "Historial de rutas de hasta 365 días",
    ],
    descripcionCorta: "Se conecta directo a la toma de 12V de autos, motos o equipos, con botón SOS integrado.",
    metaDescripcion: "GPS oculto tipo cargador que se conecta a la toma de 12V del auto o moto, con botón SOS. Historial de rutas de 365 días. Envío gratis en RD.",
    descripcionLarga:
      "Se enchufa directo a cualquier toma de 12V —el encendedor de un auto, una moto, un cuatrimoto o un equipo con salida de accesorios— y queda alimentado de forma constante, sin recargas manuales. Incluye un botón SOS físico y una batería de respaldo interna que lo mantiene reportando ubicación hasta 30 minutos si lo desconectan.",
    caracteristicas: [
      "Conexión directa a una toma de 12V, sin cables sueltos ni instalación",
      "Botón SOS físico integrado",
      "Historial de rutas de hasta 365 días",
      "Alertas de zona segura, batería baja y movimiento",
      "Batería de respaldo de hasta 30 minutos si se desconecta",
    ],
    compatibilidad: "App para iOS y Android. Incluye tarjeta SIM preinstalada.",
    cobertura: "Cobertura internacional donde exista red 4G.",
    red: "4G LTE",
    peso: "38 g",
    dimensiones: "3.2 × 3.2 × 6.0 cm",
    caja: ["1 rastreador GPS para toma de 12V", "Tarjeta SIM preinstalada", "Guía rápida"],
    garantia: "6 meses",
    ventajas: ["No requiere instalación ni cables sueltos", "Botón SOS físico integrado", "Historial de rutas de hasta 365 días"],
    desventajas: ["Necesita una toma de 12V disponible y libre", "Si el vehículo usa esa toma para otro accesorio, hay que liberarla"],
    idealPara: "Autos, motocicletas, cuatrimotos y equipos con salida de 12V.",
    faqs: [
      { p: "¿Se puede usar en motos o cuatrimotos?", r: "Sí, funciona en cualquier vehículo o equipo con una toma de 12V estándar." },
      { p: "¿Qué pasa si me lo desconectan?", r: "Tiene una batería de respaldo que lo mantiene reportando ubicación hasta por 30 minutos." },
    ],
  },
  {
    id: "gps-mini-magnetico",
    sku: "GP-MAG-C800",
    subtitulo: "Se pega, se olvida, y siempre sabes dónde está.",
    categoria: ["vehiculos", "objetos"],
    nombre: "GPS Mini+ Magnético 4G",
    linea: "Línea Vehicular",
    precio: 5490,
    precioAnterior: null,
    rating: 4.7,
    reviews: 102,
    disponibilidad: "in-stock",
    disponibilidadTexto: "Pocas unidades",
    bateriaDias: "Batería de 5,000 mAh: hasta 20 días de uso continuo, más de 90 días en reposo",
    imagen: "vehicular",
    model3d: "assets/3d/gps-cuadrado.html?v=2",
    resenas: [
      { nombre: "Estefany Contreras", ciudad: "Barahona, RD", foto: "assets/images/reviews/mini-magnetico-1.jpg", rating: 5, texto: "Todavía en la caja se ve resistente, nada plástico ni barato." },
      { nombre: "Freddy Encarnación", ciudad: "Baní, RD", foto: "assets/images/reviews/mini-magnetico-2.jpg", rating: 5, texto: "Lo tengo desde hace semanas pegado y el imán no ha soltado para nada." },
      { nombre: "Yajaira Polanco", ciudad: "Nagua, RD", foto: "assets/images/reviews/mini-magnetico-3.jpg", rating: 4, texto: "Se lo puse a la camioneta de reparto del negocio, bien discreto por dentro del guardabarros." },
    ],
    metaDescripcion: "GPS magnético 4G con batería de 5,000 mAh, hasta 20 días de uso continuo. Rastreo en tiempo real y alertas por WhatsApp. Envío gratis en RD.",
    bullets: [
      "Base magnética potente, se instala en segundos",
      "Batería de 5,000 mAh: hasta 20 días de uso continuo",
      "Rastreo en tiempo real y alertas por WhatsApp",
    ],
    descripcionCorta: "Rastreador GPS magnético 4G, con batería de larga duración y alertas por WhatsApp.",
    descripcionLarga:
      "Se instala en segundos gracias a su base magnética, en cualquier parte oculta y metálica del vehículo. Su batería de 5,000 mAh le da hasta 20 días de uso continuo y más de 90 días en reposo. Reporta la ubicación en tiempo real y avisa por WhatsApp ante batería baja, movimiento o salida de una zona segura. El precio incluye 1 año de servicio; la renovación anual es de solo RD$1,990.",
    caracteristicas: [
      "Base magnética potente para instalación rápida y oculta",
      "Ubicación en tiempo real desde la app o la web",
      "Alertas vía WhatsApp: batería baja, movimiento y velocidad",
      "Geocercas con aviso de entrada y salida de zonas",
      "Historial de recorrido con vista de imágenes del trayecto",
      "Conectividad 4G, funciona en cualquier país",
    ],
    compatibilidad: "App premium (app y web) incluida. El precio incluye 1 año de servicio; renovación anual de RD$1,990.",
    cobertura: "Funciona en cualquier país con conectividad 4G internacional.",
    red: "4G",
    peso: "85 g (aprox.)",
    dimensiones: "7.0 × 5.0 × 2.0 cm (aprox.)",
    caja: ["1 rastreador GPS magnético", "Cable de carga", "Guía rápida", "Tarjeta SIM preinstalada (1 año de servicio incluido)"],
    garantia: "6 meses",
    ventajas: ["Se instala en segundos, sin herramientas", "Batería de larga duración (hasta 20 días de uso continuo)", "Incluye 1 año de servicio en el precio"],
    desventajas: ["La renovación del servicio es anual (RD$1,990) a partir del segundo año", "Necesita una superficie metálica para la base magnética"],
    idealPara: "Autos, motos y camionetas que necesiten un GPS oculto de instalación rápida.",
    faqs: [
      { p: "¿Tengo que pagar todos los meses?", r: "No — el precio incluye 1 año completo de servicio. Después, la renovación anual es de solo RD$1,990." },
      { p: "¿Cómo se instala?", r: "Se coloca con su base magnética en un lugar oculto del vehículo, en segundos y sin herramientas." },
    ],
  },
  {
    id: "gps-super-magnetico",
    sku: "GP-MAG-C1450",
    subtitulo: "Mayor imán, mayor batería, para el trabajo que no puede fallar.",
    categoria: ["vehiculos", "objetos"],
    nombre: "GPS Súper Magnético 4G PRO",
    linea: "Línea Vehicular",
    precio: 7990,
    precioAnterior: null,
    rating: 4.8,
    reviews: 67,
    disponibilidad: "in-stock",
    disponibilidadTexto: "Pocas unidades",
    bateriaDias: "Batería de 10,000 mAh: hasta 35 días de uso continuo, más de 90 días en reposo",
    imagen: "vehicular",
    model3d: "assets/3d/gps-cuadrado-pro.html?v=2",
    resenas: [
      { nombre: "Héctor Manuel Rosario", ciudad: "Azua, RD", foto: "assets/images/reviews/super-magnetico-1.jpg", rating: 5, texto: "El PRO se nota más grande y más serio que el otro que tenía antes, vale la pena la diferencia." },
      { nombre: "Scarlet Abreu", ciudad: "Cotuí, RD", foto: "assets/images/reviews/super-magnetico-2.jpg", rating: 5, texto: "Se ve bien resistente, como para aguantar golpes y agua sin problema." },
      { nombre: "Josué Ureña", ciudad: "Constanza, RD", foto: "assets/images/reviews/super-magnetico-3.jpg", rating: 5, texto: "Los imanes son una barbaridad de fuertes, lo pegué al chasis del camión y no se mueve ni con bache." },
    ],
    metaDescripcion: "GPS súper magnético 4G con batería de 10,000 mAh, hasta 35 días de uso continuo. Imán extra fuerte y alertas por WhatsApp. Envío gratis en RD.",
    bullets: [
      "Imán extra fuerte, se instala en segundos",
      "Batería de 10,000 mAh: hasta 35 días de uso continuo",
      "Rastreo en tiempo real y alertas por WhatsApp",
    ],
    descripcionCorta: "Rastreador GPS magnético 4G de alta capacidad, con imán extra fuerte y batería de larga duración.",
    descripcionLarga:
      "La versión PRO de nuestro GPS magnético, con imán extra fuerte para quedar bien sujeto incluso en superficies difíciles, y una batería de 10,000 mAh que da hasta 35 días de uso continuo y más de 90 días en reposo. Reporta la ubicación en tiempo real y avisa por WhatsApp ante batería baja, movimiento o salida de una zona segura. El precio incluye 1 año de servicio; la renovación anual es de solo RD$1,990.",
    caracteristicas: [
      "Imán extra fuerte, ideal para instalaciones más exigentes",
      "Batería ultra grande de 10,000 mAh",
      "Ubicación en tiempo real desde la app o la web",
      "Alertas vía WhatsApp: batería baja, movimiento y velocidad",
      "Geocercas con aviso de entrada y salida de zonas",
      "Historial de recorrido con vista de imágenes del trayecto",
      "Conectividad 4G, funciona en cualquier país",
    ],
    compatibilidad: "App premium (app y web) incluida. El precio incluye 1 año de servicio; renovación anual de RD$1,990.",
    cobertura: "Funciona en cualquier país con conectividad 4G internacional.",
    red: "4G",
    peso: "110 g (aprox.)",
    dimensiones: "8.5 × 6.0 × 2.5 cm (aprox.)",
    caja: ["1 rastreador GPS magnético PRO", "Cable de carga", "Guía rápida", "Tarjeta SIM preinstalada (1 año de servicio incluido)"],
    garantia: "6 meses",
    ventajas: ["Imán mucho más fuerte que el modelo estándar", "Batería de mayor duración (hasta 35 días de uso continuo)", "Incluye 1 año de servicio en el precio"],
    desventajas: ["Más grande y pesado que el modelo Mini+", "La renovación del servicio es anual (RD$1,990) a partir del segundo año"],
    idealPara: "Vehículos de trabajo, camiones y equipos que necesitan un GPS oculto con mayor autonomía y sujeción.",
    faqs: [
      { p: "¿En qué se diferencia del GPS Mini+ Magnético?", r: "Tiene un imán más fuerte y una batería más grande (10,000 mAh vs. 5,000 mAh), con más días de uso continuo." },
      { p: "¿Tengo que pagar todos los meses?", r: "No — el precio incluye 1 año completo de servicio. Después, la renovación anual es de solo RD$1,990." },
    ],
  },
  {
    id: "salind-11-4g",
    sku: "GP-SAL-11",
    subtitulo: "Resistente al agua y listo para acompañar cualquier vehículo, en cualquier clima.",
    categoria: ["vehiculos", "objetos"],
    nombre: "SALIND 11 GPS 4G Magnético",
    linea: "Línea Vehicular",
    precio: 6370,
    precioAnterior: null,
    rating: 4.6,
    reviews: 140,
    disponibilidad: "in-stock",
    disponibilidadTexto: "Pocas unidades",
    bateriaDias: "Batería de 7,500 mAh: hasta 40 días con uso activo (~1 h/día), hasta 70 días en reposo",
    imagen: "vehicular",
    model3d: "assets/3d/salind-11-4g.html?v=2",
    resenas: [
      { nombre: "Miguelina Disla", ciudad: "Jarabacoa, RD", foto: "assets/images/reviews/salind-11-1.jpg", rating: 5, texto: "Me lo mandaron rapidito y se ve bien terminado, nada de plástico flojo." },
      { nombre: "Franklin Rosario", ciudad: "Villa Altagracia, RD", foto: "assets/images/reviews/salind-11-2.jpg", rating: 4, texto: "El logo de Salind se ve grabado de verdad, no pegado como sticker." },
      { nombre: "Ana Belkis Checo", ciudad: "Bávaro, RD", foto: "assets/images/reviews/salind-11-3.jpg", rating: 5, texto: "Lo tengo pegado abajo del carro hace un mes y ahí sigue, ni con lluvia se ha caído." },
    ],
    metaDescripcion: "SALIND 11 GPS 4G magnético, resistente al agua, para autos y flotas. Batería de 7,500 mAh, hasta 70 días en reposo. Requiere suscripción de datos.",
    bullets: [
      "Imanes súper fuertes, se fija en segundos",
      "Batería de 7,500 mAh: hasta 70 días en reposo",
      "Resistente al agua y a salpicaduras",
    ],
    descripcionCorta: "GPS magnético 4G, resistente al agua, con batería de larga duración para autos, botes y flotas.",
    descripcionLarga:
      "El SALIND 11 se fija en segundos gracias a sus imanes integrados, con un agarre estable en autos, botes u otro vehículo. Es robusto y resistente al agua y a las salpicaduras. Su batería de 7,500 mAh dura hasta 40 días con un uso activo de aproximadamente 1 hora al día, y hasta 70 días en reposo. Trae la tarjeta SIM ya integrada (cobertura en EE. UU. y el resto del mundo), pero requiere una suscripción activa al plan de rastreo para funcionar.",
    caracteristicas: [
      "Imanes súper fuertes para instalación rápida en cualquier superficie adecuada",
      "Resistente al agua y a salpicaduras",
      "Geocercas, límites de velocidad y alertas de batería baja o vibración",
      "Historial de rutas y kilometraje, ideal también para flotas",
      "Aplicación para iOS/Android y portal web",
      "Conectividad 4G LTE con cobertura en EE. UU. y el resto del mundo",
    ],
    compatibilidad: "Incluye tarjeta SIM ya integrada. Requiere una suscripción activa al plan de rastreo (planes Básico o Premium) para reportar ubicación.",
    cobertura: "Cobertura en Estados Unidos y a nivel mundial, según el plan de rastreo activo.",
    red: "4G LTE",
    peso: "No especificado por el fabricante",
    dimensiones: "No especificado por el fabricante",
    caja: ["1 rastreador GPS SALIND 11", "Tarjeta SIM ya integrada", "Cable de carga"],
    garantia: "6 meses",
    ventajas: ["Imanes muy fuertes, agarre estable", "Resistente al agua", "Batería de larga duración en reposo (hasta 70 días)"],
    desventajas: ["Requiere una suscripción activa al plan de rastreo para funcionar", "El precio y peso/dimensiones exactas están pendientes de confirmar"],
    idealPara: "Autos, botes y flotas que necesiten un rastreador magnético resistente al agua.",
    faqs: [
      { p: "¿Necesito pagar una suscripción?", r: "Sí, el dispositivo ya trae la SIM integrada, pero necesita un plan de rastreo activo (desde planes básicos) para reportar ubicación." },
      { p: "¿Sirve para botes?", r: "Sí, gracias a que es resistente al agua y se fija con imanes, funciona bien en botes además de autos y flotas." },
    ],
  },
  {
    id: "seeworld-p2",
    sku: "GP-SEE-P2",
    subtitulo: "Más que ubicación: cuida también la salud de tu mascota.",
    categoria: ["mascotas"],
    nombre: "SEEWORLD P2 GPS para Mascotas",
    linea: "Línea Mascotas",
    precio: 7990,
    precioAnterior: null,
    rating: 4.6,
    reviews: 58,
    disponibilidad: "in-stock",
    disponibilidadTexto: "Pocas unidades",
    bateriaDias: "Batería de 800 mAh: hasta 10 días de uso",
    imagen: "mascota",
    model3d: "assets/3d/seeworld-p2.html?v=2",
    resenas: [
      { nombre: "Rafael Antonio Mejía", ciudad: "Sabana Grande de Boyá, RD", foto: "assets/images/reviews/seeworld-p2-1.jpg", rating: 5, texto: "Lo compré para mi perro y en la caja sale bien explicado todo lo que hace, hasta lo de la salud." },
      { nombre: "Yesenia Paulino", ciudad: "San Pedro de Macorís, RD", foto: "assets/images/reviews/seeworld-p2-2.jpg", rating: 5, texto: "Bien chiquito y liviano, mi gato ni se dio cuenta que lo tenía puesto." },
      { nombre: "Elvin Payano", ciudad: "Santiago, RD", foto: "assets/images/reviews/seeworld-p2-3.jpg", rating: 4, texto: "Llegó bien empacado en su cajita azul, se nota que es de marca reconocida." },
    ],
    metaDescripcion: "SEEWORLD P2, GPS para perros y gatos con monitoreo de salud (sueño, actividad, calorías). Resistente al agua IP67, batería de 10 días. Envío gratis en RD.",
    bullets: [
      "Monitoreo de salud: sueño, actividad y calorías",
      "Resistente al agua, certificación IP67",
      "Ubicación en tiempo real, conectividad 2G/4G",
    ],
    descripcionCorta: "GPS para perros y gatos con monitoreo de salud avanzado, resistente al agua.",
    descripcionLarga:
      "Diseñado para perros y gatos de más de 4 kg, el SEEWORLD P2 no solo ubica a tu mascota en tiempo real: también monitorea su tiempo de actividad, calorías quemadas y sueño. Es compacto, resistente al agua (IP67) y trabaja con conectividad 2G y 4G para mantenerse conectado incluso en zonas con señal débil. Su batería de 800 mAh dura hasta 10 días de uso. Para funcionar necesita una suscripción mensual a la aplicación COOLPET (no incluida en el precio del equipo).",
    caracteristicas: [
      "Monitoreo de salud: tiempo de actividad, calorías y sueño",
      "Conectividad dual 2G y 4G",
      "Posicionamiento GPS/GLONASS/BDS/WiFi/LBS, precisión menor a 10 m",
      "Resistente al agua, certificación IP67",
      "Alarma de batería baja y alarma sensible a la luz",
      "Modos de funcionamiento configurables (tiempo real, inteligente, ahorro de energía, con alarma)",
    ],
    compatibilidad: "Requiere la aplicación COOLPET con suscripción mensual activa (no incluida en el precio del equipo).",
    cobertura: "Cobertura donde exista red 2G o 4G disponible.",
    red: "2G / 4G",
    peso: "34 g",
    dimensiones: "No especificado con precisión por el fabricante",
    caja: ["1 rastreador GPS SEEWORLD P2", "Cable de carga", "Guía rápida"],
    garantia: "6 meses",
    ventajas: ["Monitoreo de salud real (actividad, calorías, sueño)", "Resistente al agua (IP67)", "Doble red 2G/4G, mejor cobertura en zonas con señal débil"],
    desventajas: ["Requiere suscripción mensual aparte a la app COOLPET", "Pensado para mascotas de más de 4 kg"],
    idealPara: "Perros y gatos de más de 4 kg cuyos dueños quieran monitorear también su salud, no solo su ubicación.",
    faqs: [
      { p: "¿Necesito pagar una suscripción?", r: "Sí, este modelo requiere una suscripción mensual aparte a la aplicación COOLPET para funcionar." },
      { p: "¿Sirve para mascotas pequeñas?", r: "Está pensado para perros y gatos de más de 4 kg; en mascotas más chicas puede resultar algo grande o pesado." },
    ],
  },
];
