/**
 * products.js — Catálogo de GPS Portátiles
 * Única fuente de verdad para catálogo, tarjetas y ficha de producto.
 */

const CATEGORIA_LABEL = {
  personas: "Personas",
  vehiculos: "Vehículos",
  mascotas: "Mascotas",
  objetos: "Objetos de valor",
};

const PRODUCTS = [
  {
    id: "rastreador-personal-mini",
    sku: "GP-PER-100",
    categoria: ["personas", "objetos"],
    nombre: "Rastreador Personal Mini 4G",
    linea: "Línea Personal",
    precio: 5490,
    precioAnterior: null,
    rating: 4.7,
    reviews: 128,
    disponibilidad: "in-stock",
    disponibilidadTexto: "Pocas unidades",
    bateriaDias: "Hasta 5 días con uso diario (aprox. 1 hora activa al día)",
    imagen: "personal",
    model3d: "assets/3d/gps-personal.html",
    resenas: [
      { nombre: "Elizabeth Cruz", ciudad: "Santiago, RD", foto: "assets/images/reviews/reviewer-1-avatar.jpg", rating: 5, texto: "Se lo puse a mi mamá en la cartera y la app me marca su ubicación clarito. Fácil de configurar, ya venía con el chip." },
      { nombre: "Manuel Batista", ciudad: "Moca, RD", foto: "assets/images/reviews/reviewer-2-avatar.jpg", rating: 5, texto: "Buena batería, me dura varios días sin tener que estar cargándolo todos los días." },
      { nombre: "Carolina Núñez", ciudad: "Santo Domingo, RD", foto: "assets/images/reviews/reviewer-3-avatar.jpg", rating: 4, texto: "Funciona bien, solo hay que estar pendiente del plan para que no se quede sin servicio." },
    ],
    bullets: [
      "Ubicación en tiempo real vía red 4G LTE",
      "Tarjeta SIM ya integrada, lista para usar",
      "Resistente al agua según norma IP65",
    ],
    descripcionCorta: "Localizador compacto para adultos mayores, niños y objetos de valor, con SIM ya integrada.",
    metaDescripcion: "Localizador GPS 4G compacto para personas mayores, niños y objetos de valor. SIM ya integrada, resistente al agua IP65. Envío gratis en RD.",
    descripcionLarga:
      "Un localizador compacto (41 g) pensado para pasar desapercibido en un bolsillo o llavero. Trae la tarjeta SIM ya preconfigurada, así que no hay que gestionar un chip aparte: se activa el plan de rastreo y queda reportando ubicación en tiempo real por red 4G, con una batería que aguanta hasta 5 días de uso diario normal.",
    caracteristicas: [
      "Ubicación en tiempo real por red 4G LTE con respaldo GSM/GPRS",
      "Precisión de hasta 5 metros según recepción de señal GPS",
      "Geocercas (zonas seguras) con notificación de entrada o salida",
      "Alertas de batería baja, apagado, velocidad y movimiento",
      "Resistencia al agua según norma IP65",
    ],
    compatibilidad: "Incluye tarjeta SIM ya preconfigurada. Requiere una suscripción activa al plan de rastreo para reportar ubicación. App para iOS y Android.",
    cobertura: "Cobertura internacional con red 4G, según el plan de rastreo activo.",
    red: "4G LTE / GSM / GPRS",
    peso: "41 g",
    dimensiones: "5.4 × 3.1 × 2.0 cm",
    caja: ["1 rastreador GPS", "Tarjeta SIM ya integrada", "Cable de carga USB-C", "Guía rápida"],
    garantia: "6 meses contra defectos de fábrica",
    ventajas: ["Ya viene con SIM integrada, no hay que gestionar un chip aparte", "Diseño compacto y liviano (41 g)", "Resistente al agua IP65"],
    desventajas: ["Requiere una suscripción activa al plan de rastreo para funcionar", "La autonomía baja si el rastreo en tiempo real queda siempre activo"],
    idealPara: "Adultos mayores, niños, equipaje y objetos de valor.",
    faqs: [
      { p: "¿Necesito pagar una suscripción?", r: "El dispositivo ya incluye la SIM, pero para que reporte ubicación necesita un plan de rastreo activo." },
      { p: "¿Cuánto dura la batería?", r: "Hasta 5 días con un uso normal de rastreo diario (aprox. 1 hora activa por día)." },
    ],
  },
  {
    id: "gps-vehicular-oculto",
    sku: "GP-VEH-200",
    categoria: ["vehiculos"],
    nombre: "GPS Vehicular Oculto OBD-2",
    linea: "Línea Vehicular",
    precio: 4550,
    precioAnterior: null,
    rating: 4.8,
    reviews: 214,
    disponibilidad: "in-stock",
    disponibilidadTexto: "Pocas unidades",
    bateriaDias: "Sin recargas — se alimenta del vehículo (respaldo interno de hasta 30 min si se desconecta)",
    imagen: "vehicular",
    model3d: "assets/3d/gps-obd2.html",
    bullets: [
      "Se conecta directo al puerto OBD-II, sin cables",
      "Se alimenta del vehículo, sin recargas manuales",
      "Batería de respaldo si se desconecta",
    ],
    descripcionCorta: "Se conecta directo al puerto OBD-II del vehículo, sin cables ni instalación.",
    metaDescripcion: "GPS oculto para autos que se conecta al puerto OBD-2 en segundos, sin cables ni instalación. Se alimenta del vehículo. Envío gratis a toda RD.",
    descripcionLarga:
      "Se conecta en segundos al puerto de diagnóstico OBD-II que traen la mayoría de los autos desde 1996, sin cables ni herramientas. Queda alimentado directamente por la batería del vehículo y reporta su ubicación en tiempo real por red 4G, con una batería de respaldo interna que lo mantiene reportando hasta 30 minutos si lo desconectan o lo remueven del puerto.",
    caracteristicas: [
      "Instalación tipo plug & play en el puerto OBD-II, sin cables",
      "Alimentación directa desde el vehículo, sin recargas manuales",
      "Batería de respaldo interna (hasta 30 min) ante una desconexión",
      "Alertas de exceso de velocidad, vibración y remoción del puerto",
      "Compatible con un amplio rango de voltaje (9–36V): autos, camionetas y flotillas",
    ],
    compatibilidad: "Compatible con vehículos con puerto OBD-II estándar (la mayoría de autos desde 1996). Panel web y app móvil incluidos.",
    cobertura: "Cobertura donde exista señal celular 4G, con reporte en tiempo real.",
    red: "4G LTE",
    peso: "45 g",
    dimensiones: "5.0 × 3.0 × 2.0 cm",
    caja: ["1 rastreador GPS OBD-II", "Guía de instalación", "Funda protectora"],
    garantia: "6 meses, incluye soporte técnico remoto",
    ventajas: ["Se instala solo, en segundos, sin herramientas", "No requiere recargas: se alimenta del vehículo", "Discreto dentro del tablero, difícil de notar a simple vista"],
    desventajas: ["Solo compatible con vehículos que tengan puerto OBD-II estándar", "Si lo desconectan del puerto, la batería de respaldo dura poco (30 min)"],
    idealPara: "Autos particulares, camionetas de trabajo y flotillas pequeñas con puerto OBD-II.",
    faqs: [
      { p: "¿Necesito conectarlo a la batería del auto?", r: "No, se conecta directo al puerto OBD-II y se alimenta desde ahí; no requiere cableado adicional." },
      { p: "¿Qué pasa si lo desconectan?", r: "Tiene una batería de respaldo interna que lo mantiene reportando ubicación hasta por 30 minutos tras la desconexión." },
    ],
  },
  {
    id: "rastreador-mini-tag",
    sku: "GP-TAG-300",
    categoria: ["objetos", "mascotas"],
    nombre: "Rastreador Mini TAG",
    linea: "Línea Mini Tag",
    precio: 2490,
    precioAnterior: null,
    rating: 4.6,
    reviews: 96,
    disponibilidad: "in-stock",
    disponibilidadTexto: "Pocas unidades",
    bateriaDias: "Hasta 3 años de batería, sin recargas",
    imagen: "mascota",
    model3d: "assets/3d/gps-redondo.html",
    resenas: [
      { nombre: "Manuel Batista", ciudad: "Moca, RD", foto: "assets/images/reviews/reviewer-2-avatar.jpg", rating: 5, texto: "Pensé que era más grande, pero me sorprendió. ¡Es súper pequeño! Ideal para lo que lo quería." },
      { nombre: "Elizabeth Cruz", ciudad: "Santiago, RD", foto: "assets/images/reviews/reviewer-1-avatar.jpg", rating: 5, texto: "Jajaja, bueno... ojalá que mi esposo no me esté ocultando nada. Quedó súper bien escondido debajo del asiento del vehículo." },
      { nombre: "Carolina Núñez", ciudad: "Santo Domingo, RD", foto: "assets/images/reviews/reviewer-3-avatar.jpg", rating: 5, texto: "Compré varios para mis hijos y mis mascotas. Funcionan de maravilla, la aplicación es muy fácil de usar y ahora me siento mucho más tranquila porque sé dónde están todos." },
    ],
    resenas: [
      { nombre: "Elizabeth Cruz", ciudad: "Santiago, RD", foto: "assets/images/reviews/reviewer-1-avatar.jpg", rating: 5, texto: "Se lo instalé yo mismo al carro en 5 minutos, ni tuve que llevarlo a un taller." },
      { nombre: "Manuel Batista", ciudad: "Moca, RD", foto: "assets/images/reviews/reviewer-2-avatar.jpg", rating: 5, texto: "Lo tengo escondido debajo del timón, nadie lo nota y me manda la ubicación al momento." },
      { nombre: "Carolina Núñez", ciudad: "Santo Domingo, RD", foto: "assets/images/reviews/reviewer-3-avatar.jpg", rating: 5, texto: "Se alimenta del carro, no hay que estarlo cargando como otros que he tenido antes." },
    ],
    bullets: [
      "Hasta 3 años de batería, sin recargas",
      "No requiere tarjeta SIM ni pagos mensuales",
      "Discreto: no lo detectan los escáneres de rastreadores de los celulares",
    ],
    descripcionCorta: "Localizador mini y discreto, con hasta 3 años de batería y sin pagos mensuales.",
    metaDescripcion: "Mini localizador GPS sin SIM ni mensualidad, batería de hasta 3 años. Ideal para llaves, mochilas, bicicletas y mascotas. Envío gratis en RD.",
    descripcionLarga:
      "Un localizador mini y discreto, del tamaño de una moneda grande, que puedes llevar en las llaves, la mochila, la bici o sujeto al collar de una mascota. A diferencia de otros rastreadores, no necesita tarjeta SIM ni una suscripción mensual: la batería dura hasta 3 años sin recargar. Guarda el historial de recorrido, avisa si sale de una zona segura configurada y funciona en cualquier país gracias a su conectividad internacional.",
    caracteristicas: [
      "Hasta 3 años de batería, sin necesidad de recarga",
      "No requiere tarjeta SIM ni pagos mensuales",
      "Historial de recorrido y ubicación precisa",
      "Alertas al salir de zonas seguras configuradas",
      "Conectividad internacional: funciona en cualquier país",
      "Discreto, no es detectado por los escáneres de rastreadores de los celulares",
    ],
    compatibilidad: "Compatible con app móvil para iOS y Android. No requiere SIM ni plan de datos.",
    cobertura: "Cobertura internacional, funciona en cualquier país sin configuración adicional.",
    red: "Conectividad internacional propia (sin SIM ni datos móviles)",
    peso: "38 g",
    dimensiones: "4.5 × 3.2 × 1.6 cm",
    caja: ["1 localizador GPS", "Guía rápida"],
    garantia: "6 meses",
    ventajas: ["Batería de hasta 3 años, no hay que recargarlo", "Sin pagos mensuales ni SIM que gestionar", "Discreto y difícil de detectar"],
    desventajas: ["Al no usar SIM propia, depende de la red de conectividad internacional del fabricante para reportar ubicación", "No incluye soporte de collar; para usarlo en una mascota hay que conseguir uno aparte"],
    idealPara: "Llaves, mochilas, bicicletas, mascotas y cualquier objeto que no quieras perder de vista.",
    faqs: [
      { p: "¿Necesito pagar una suscripción?", r: "No, este modelo no requiere tarjeta SIM ni pagos mensuales." },
      { p: "¿Cuánto dura la batería?", r: "Hasta 3 años según el uso, sin necesidad de recargarlo." },
    ],
  },
  {
    id: "rastreador-objetos-valor",
    sku: "GP-OBJ-600",
    categoria: ["objetos", "vehiculos"],
    nombre: "GPS Oculto Tipo Cargador ValueTrack",
    linea: "Línea Objetos",
    precio: 4990,
    precioAnterior: null,
    rating: 4.5,
    reviews: 61,
    disponibilidad: "in-stock",
    disponibilidadTexto: "Pocas unidades",
    bateriaDias: "Batería de respaldo de 30 min si se desconecta de la toma de 12V",
    imagen: "objeto",
    model3d: "assets/3d/gps-cargador.html",
    resenas: [
      { nombre: "Elizabeth Cruz", ciudad: "Santiago, RD", foto: "assets/images/reviews/reviewer-1-avatar.jpg", rating: 5, texto: "Se conecta directo al encendedor del carro, súper simple de usar." },
      { nombre: "Manuel Batista", ciudad: "Moca, RD", foto: "assets/images/reviews/reviewer-2-avatar.jpg", rating: 5, texto: "Le di clic al botón SOS de prueba y llegó la alerta al momento, se siente confiable." },
      { nombre: "Carolina Núñez", ciudad: "Santo Domingo, RD", foto: "assets/images/reviews/reviewer-3-avatar.jpg", rating: 5, texto: "Práctico para la moto también, no necesita instalación complicada." },
    ],
    resenas: [
      { nombre: "Elizabeth Cruz", ciudad: "Santiago, RD", foto: "assets/images/reviews/reviewer-1-avatar.jpg", rating: 5, texto: "Lo uso para controlar las camionetas del negocio, el panel web es fácil de manejar." },
      { nombre: "Manuel Batista", ciudad: "Moca, RD", foto: "assets/images/reviews/reviewer-2-avatar.jpg", rating: 4, texto: "Funciona bien para varias unidades a la vez, aunque la primera configuración toma su tiempo." },
      { nombre: "Carolina Núñez", ciudad: "Santo Domingo, RD", foto: "assets/images/reviews/reviewer-3-avatar.jpg", rating: 5, texto: "Nos ayudó a organizar mejor las rutas de entrega de la empresa." },
    ],
    resenas: [
      { nombre: "Elizabeth Cruz", ciudad: "Santiago, RD", foto: "assets/images/reviews/reviewer-1-avatar.jpg", rating: 5, texto: "Se lo puse a la moto de mi esposo y quedamos tranquilos cuando la deja parqueada en la calle." },
      { nombre: "Manuel Batista", ciudad: "Moca, RD", foto: "assets/images/reviews/reviewer-2-avatar.jpg", rating: 5, texto: "Resistente, le ha caído agua y sigue funcionando sin problema." },
      { nombre: "Carolina Núñez", ciudad: "Santo Domingo, RD", foto: "assets/images/reviews/reviewer-3-avatar.jpg", rating: 5, texto: "Las alertas de movimiento llegan rápido al celular, muy útil." },
    ],
    bullets: [
      "Se conecta directo a la toma de 12V, sin instalación",
      "Botón SOS físico integrado",
      "Historial de rutas de hasta 365 días",
    ],
    descripcionCorta: "Se conecta directo a la toma de 12V de autos, motos o equipos, con botón SOS integrado.",
    metaDescripcion: "GPS oculto tipo cargador que se conecta a la toma de 12V del auto o moto, con botón SOS. Historial de rutas de 365 días. Envío gratis en RD.",
    descripcionLarga:
      "Se enchufa directo a cualquier toma de 12V —el encendedor de un auto, una moto, un cuatrimoto o un equipo con salida de accesorios— y queda alimentado de forma constante, sin recargas manuales. Incluye un botón SOS físico y una batería de respaldo interna que lo mantiene reportando ubicación hasta 30 minutos si lo desconectan.",
    caracteristicas: [
      "Conexión directa a una toma de 12V, sin cables sueltos ni instalación",
      "Botón SOS físico integrado",
      "Historial de rutas de hasta 365 días",
      "Alertas de zona segura, batería baja y movimiento",
      "Batería de respaldo de hasta 30 minutos si se desconecta",
    ],
    compatibilidad: "App para iOS y Android. Incluye tarjeta SIM preinstalada.",
    cobertura: "Cobertura internacional donde exista red 4G.",
    red: "4G LTE",
    peso: "38 g",
    dimensiones: "3.2 × 3.2 × 6.0 cm",
    caja: ["1 rastreador GPS para toma de 12V", "Tarjeta SIM preinstalada", "Guía rápida"],
    garantia: "6 meses",
    ventajas: ["No requiere instalación ni cables sueltos", "Botón SOS físico integrado", "Historial de rutas de hasta 365 días"],
    desventajas: ["Necesita una toma de 12V disponible y libre", "Si el vehículo usa esa toma para otro accesorio, hay que liberarla"],
    idealPara: "Autos, motocicletas, cuatrimotos y equipos con salida de 12V.",
    faqs: [
      { p: "¿Se puede usar en motos o cuatrimotos?", r: "Sí, funciona en cualquier vehículo o equipo con una toma de 12V estándar." },
      { p: "¿Qué pasa si me lo desconectan?", r: "Tiene una batería de respaldo que lo mantiene reportando ubicación hasta por 30 minutos." },
    ],
  },
  {
    id: "gps-mini-magnetico",
    sku: "GP-MAG-C800",
    categoria: ["vehiculos", "objetos"],
    nombre: "GPS Mini+ Magnético 4G",
    linea: "Línea Vehicular",
    precio: 5490,
    precioAnterior: null,
    rating: 4.7,
    reviews: 102,
    disponibilidad: "in-stock",
    disponibilidadTexto: "Pocas unidades",
    bateriaDias: "Batería de 5,000 mAh: hasta 20 días de uso continuo, más de 90 días en reposo",
    imagen: "vehicular",
    model3d: "assets/3d/gps-cuadrado.html",
    metaDescripcion: "GPS magnético 4G con batería de 5,000 mAh, hasta 20 días de uso continuo. Rastreo en tiempo real y alertas por WhatsApp. Envío gratis en RD.",
    bullets: [
      "Base magnética potente, se instala en segundos",
      "Batería de 5,000 mAh: hasta 20 días de uso continuo",
      "Rastreo en tiempo real y alertas por WhatsApp",
    ],
    descripcionCorta: "Rastreador GPS magnético 4G, con batería de larga duración y alertas por WhatsApp.",
    descripcionLarga:
      "Se instala en segundos gracias a su base magnética, en cualquier parte oculta y metálica del vehículo. Su batería de 5,000 mAh le da hasta 20 días de uso continuo y más de 90 días en reposo. Reporta la ubicación en tiempo real y avisa por WhatsApp ante batería baja, movimiento o salida de una zona segura. El precio incluye 1 año de servicio; la renovación anual es de solo RD$1,990.",
    caracteristicas: [
      "Base magnética potente para instalación rápida y oculta",
      "Ubicación en tiempo real desde la app o la web",
      "Alertas vía WhatsApp: batería baja, movimiento y velocidad",
      "Geocercas con aviso de entrada y salida de zonas",
      "Historial de recorrido con vista de imágenes del trayecto",
      "Conectividad 4G, funciona en cualquier país",
    ],
    compatibilidad: "App premium (app y web) incluida. El precio incluye 1 año de servicio; renovación anual de RD$1,990.",
    cobertura: "Funciona en cualquier país con conectividad 4G internacional.",
    red: "4G",
    peso: "85 g (aprox.)",
    dimensiones: "7.0 × 5.0 × 2.0 cm (aprox.)",
    caja: ["1 rastreador GPS magnético", "Cable de carga", "Guía rápida", "Tarjeta SIM preinstalada (1 año de servicio incluido)"],
    garantia: "6 meses",
    ventajas: ["Se instala en segundos, sin herramientas", "Batería de larga duración (hasta 20 días de uso continuo)", "Incluye 1 año de servicio en el precio"],
    desventajas: ["La renovación del servicio es anual (RD$1,990) a partir del segundo año", "Necesita una superficie metálica para la base magnética"],
    idealPara: "Autos, motos y camionetas que necesiten un GPS oculto de instalación rápida.",
    faqs: [
      { p: "¿Tengo que pagar todos los meses?", r: "No — el precio incluye 1 año completo de servicio. Después, la renovación anual es de solo RD$1,990." },
      { p: "¿Cómo se instala?", r: "Se coloca con su base magnética en un lugar oculto del vehículo, en segundos y sin herramientas." },
    ],
    resenas: [
      { nombre: "Elizabeth Cruz", ciudad: "Santiago, RD", foto: "assets/images/reviews/reviewer-1-avatar.jpg", rating: 5, texto: "Se pega bien fuerte, lo puse debajo del carro y ahí sigue después de varias semanas manejando por toda clase de calle." },
      { nombre: "Manuel Batista", ciudad: "Moca, RD", foto: "assets/images/reviews/reviewer-2-avatar.jpg", rating: 5, texto: "La batería de verdad dura, ya tiene como dos semanas sin cargarlo y sigue reportando normal." },
      { nombre: "Carolina Núñez", ciudad: "Santo Domingo, RD", foto: "assets/images/reviews/reviewer-3-avatar.jpg", rating: 4, texto: "Funciona bien, me gustó que ya venga con SIM y todo listo. Lo único es que hay que estar pendiente de la renovación del año." },
    ],
  },
  {
    id: "gps-super-magnetico",
    sku: "GP-MAG-C1450",
    categoria: ["vehiculos", "objetos"],
    nombre: "GPS Súper Magnético 4G PRO",
    linea: "Línea Vehicular",
    precio: 7990,
    precioAnterior: null,
    rating: 4.8,
    reviews: 67,
    disponibilidad: "in-stock",
    disponibilidadTexto: "Pocas unidades",
    bateriaDias: "Batería de 10,000 mAh: hasta 35 días de uso continuo, más de 90 días en reposo",
    imagen: "vehicular",
    model3d: "assets/3d/gps-cuadrado-pro.html",
    metaDescripcion: "GPS súper magnético 4G con batería de 10,000 mAh, hasta 35 días de uso continuo. Imán extra fuerte y alertas por WhatsApp. Envío gratis en RD.",
    bullets: [
      "Imán extra fuerte, se instala en segundos",
      "Batería de 10,000 mAh: hasta 35 días de uso continuo",
      "Rastreo en tiempo real y alertas por WhatsApp",
    ],
    descripcionCorta: "Rastreador GPS magnético 4G de alta capacidad, con imán extra fuerte y batería de larga duración.",
    descripcionLarga:
      "La versión PRO de nuestro GPS magnético, con imán extra fuerte para quedar bien sujeto incluso en superficies difíciles, y una batería de 10,000 mAh que da hasta 35 días de uso continuo y más de 90 días en reposo. Reporta la ubicación en tiempo real y avisa por WhatsApp ante batería baja, movimiento o salida de una zona segura. El precio incluye 1 año de servicio; la renovación anual es de solo RD$1,990.",
    caracteristicas: [
      "Imán extra fuerte, ideal para instalaciones más exigentes",
      "Batería ultra grande de 10,000 mAh",
      "Ubicación en tiempo real desde la app o la web",
      "Alertas vía WhatsApp: batería baja, movimiento y velocidad",
      "Geocercas con aviso de entrada y salida de zonas",
      "Historial de recorrido con vista de imágenes del trayecto",
      "Conectividad 4G, funciona en cualquier país",
    ],
    compatibilidad: "App premium (app y web) incluida. El precio incluye 1 año de servicio; renovación anual de RD$1,990.",
    cobertura: "Funciona en cualquier país con conectividad 4G internacional.",
    red: "4G",
    peso: "110 g (aprox.)",
    dimensiones: "8.5 × 6.0 × 2.5 cm (aprox.)",
    caja: ["1 rastreador GPS magnético PRO", "Cable de carga", "Guía rápida", "Tarjeta SIM preinstalada (1 año de servicio incluido)"],
    garantia: "6 meses",
    ventajas: ["Imán mucho más fuerte que el modelo estándar", "Batería de mayor duración (hasta 35 días de uso continuo)", "Incluye 1 año de servicio en el precio"],
    desventajas: ["Más grande y pesado que el modelo Mini+", "La renovación del servicio es anual (RD$1,990) a partir del segundo año"],
    idealPara: "Vehículos de trabajo, camiones y equipos que necesitan un GPS oculto con mayor autonomía y sujeción.",
    faqs: [
      { p: "¿En qué se diferencia del GPS Mini+ Magnético?", r: "Tiene un imán más fuerte y una batería más grande (10,000 mAh vs. 5,000 mAh), con más días de uso continuo." },
      { p: "¿Tengo que pagar todos los meses?", r: "No — el precio incluye 1 año completo de servicio. Después, la renovación anual es de solo RD$1,990." },
    ],
    resenas: [
      { nombre: "Elizabeth Cruz", ciudad: "Santiago, RD", foto: "assets/images/reviews/reviewer-1-avatar.jpg", rating: 5, texto: "Este es más grande que el otro que había comprado antes, pero el imán agarra muchísimo mejor, no se despega ni en carretera." },
      { nombre: "Manuel Batista", ciudad: "Moca, RD", foto: "assets/images/reviews/reviewer-2-avatar.jpg", rating: 5, texto: "La batería aguanta un montón, lo cargué una vez y ya llevo semanas sin volver a tocarlo." },
      { nombre: "Carolina Núñez", ciudad: "Santo Domingo, RD", foto: "assets/images/reviews/reviewer-3-avatar.jpg", rating: 4, texto: "Bueno para el camión de la empresa, pesa un poco más que uno chiquito pero para eso es, para quedarse fijo." },
    ],
  },
  {
    id: "salind-11-4g",
    sku: "GP-SAL-11",
    categoria: ["vehiculos", "objetos"],
    nombre: "SALIND 11 GPS 4G Magnético",
    linea: "Línea Vehicular",
    precio: 0,
    precioAnterior: null,
    rating: 4.6,
    reviews: 140,
    disponibilidad: "in-stock",
    disponibilidadTexto: "Pocas unidades",
    bateriaDias: "Batería de 7,500 mAh: hasta 40 días con uso activo (~1 h/día), hasta 70 días en reposo",
    imagen: "vehicular",
    model3d: "assets/3d/salind-11-4g.html",
    metaDescripcion: "SALIND 11 GPS 4G magnético, resistente al agua, para autos y flotas. Batería de 7,500 mAh, hasta 70 días en reposo. Requiere suscripción de datos.",
    bullets: [
      "Imanes súper fuertes, se fija en segundos",
      "Batería de 7,500 mAh: hasta 70 días en reposo",
      "Resistente al agua y a salpicaduras",
    ],
    descripcionCorta: "GPS magnético 4G, resistente al agua, con batería de larga duración para autos, botes y flotas.",
    descripcionLarga:
      "El SALIND 11 se fija en segundos gracias a sus imanes integrados, con un agarre estable en autos, botes u otro vehículo. Es robusto y resistente al agua y a las salpicaduras. Su batería de 7,500 mAh dura hasta 40 días con un uso activo de aproximadamente 1 hora al día, y hasta 70 días en reposo. Trae la tarjeta SIM ya integrada (cobertura en EE. UU. y el resto del mundo), pero requiere una suscripción activa al plan de rastreo para funcionar.",
    caracteristicas: [
      "Imanes súper fuertes para instalación rápida en cualquier superficie adecuada",
      "Resistente al agua y a salpicaduras",
      "Geocercas, límites de velocidad y alertas de batería baja o vibración",
      "Historial de rutas y kilometraje, ideal también para flotas",
      "Aplicación para iOS/Android y portal web",
      "Conectividad 4G LTE con cobertura en EE. UU. y el resto del mundo",
    ],
    compatibilidad: "Incluye tarjeta SIM ya integrada. Requiere una suscripción activa al plan de rastreo (planes Básico o Premium) para reportar ubicación.",
    cobertura: "Cobertura en Estados Unidos y a nivel mundial, según el plan de rastreo activo.",
    red: "4G LTE",
    peso: "No especificado por el fabricante",
    dimensiones: "No especificado por el fabricante",
    caja: ["1 rastreador GPS SALIND 11", "Tarjeta SIM ya integrada", "Cable de carga"],
    garantia: "6 meses",
    ventajas: ["Imanes muy fuertes, agarre estable", "Resistente al agua", "Batería de larga duración en reposo (hasta 70 días)"],
    desventajas: ["Requiere una suscripción activa al plan de rastreo para funcionar", "El precio y peso/dimensiones exactas están pendientes de confirmar"],
    idealPara: "Autos, botes y flotas que necesiten un rastreador magnético resistente al agua.",
    faqs: [
      { p: "¿Necesito pagar una suscripción?", r: "Sí, el dispositivo ya trae la SIM integrada, pero necesita un plan de rastreo activo (desde planes básicos) para reportar ubicación." },
      { p: "¿Sirve para botes?", r: "Sí, gracias a que es resistente al agua y se fija con imanes, funciona bien en botes además de autos y flotas." },
    ],
    resenas: [
      { nombre: "Elizabeth Cruz", ciudad: "Santiago, RD", foto: "assets/images/reviews/reviewer-1-avatar.jpg", rating: 5, texto: "Lo probé en el bote de mi papá y ahí sigue pegado, resiste bien el agua y el sol." },
      { nombre: "Manuel Batista", ciudad: "Moca, RD", foto: "assets/images/reviews/reviewer-2-avatar.jpg", rating: 4, texto: "El imán agarra fuerte de verdad. Lo único es que hay que estar pendiente del plan para que no se quede sin reportar." },
      { nombre: "Carolina Núñez", ciudad: "Santo Domingo, RD", foto: "assets/images/reviews/reviewer-3-avatar.jpg", rating: 5, texto: "La batería aguanta bastante en reposo, no he tenido que cargarlo seguido." },
    ],
  },
];
